# Uncomment this line to define a global platform for your project
platform :ios, '8.1.1'
# Uncomment this line if you're using Swift
 use_frameworks!

pod 'Alamofire'
pod 'OpenCV'

target 'FamitoryForBotch' do

end

target 'FamitoryForBotchTests' do

end

target 'FamitoryForBotchUITests' do

end

